# Generated by Django 5.0.6 on 2026-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='family_income',
            field=models.CharField(choices=[('low', 'Below 2.5 LPA'), ('medium', '2.5-5 LPA'), ('high', '5-10 LPA'), ('very_high', 'Above 10 LPA')], default='medium', max_length=20),
        ),
    ]
