# Generated by Django 5.0.6 on 2026-05-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('internal1', 'Internal Assessment 1'), ('internal2', 'Internal Assessment 2'), ('internal3', 'Internal Assessment 3'), ('external', 'End Semester Exam')], max_length=10)),
                ('marks_obtained', models.FloatField()),
                ('maximum_marks', models.FloatField(default=100)),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'exam_type')},
            },
        ),
    ]
